/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteCookiesRouteImport } from './routes/_site/cookies'
import { Route as SiteGamesRouteImport } from './routes/_site/games'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as SiteVisitRouteImport } from './routes/_site/visit'
import { Route as SiteExploreIndexRouteImport } from './routes/_site/explore/index'
import { Route as SiteExploreComicsRouteImport } from './routes/_site/explore/comics'
import { Route as SiteExploreEventsRouteImport } from './routes/_site/explore/events'
import { Route as SiteExploreFoodRouteImport } from './routes/_site/explore/food'
import { Route as SiteExploreLegosRouteImport } from './routes/_site/explore/legos'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCookiesRoute = SiteCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGamesRoute = SiteGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVisitRoute = SiteVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExploreIndexRoute = SiteExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExploreComicsRoute = SiteExploreComicsRouteImport.update({
  id: '/explore/comics',
  path: '/explore/comics',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExploreEventsRoute = SiteExploreEventsRouteImport.update({
  id: '/explore/events',
  path: '/explore/events',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExploreFoodRoute = SiteExploreFoodRouteImport.update({
  id: '/explore/food',
  path: '/explore/food',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExploreLegosRoute = SiteExploreLegosRouteImport.update({
  id: '/explore/legos',
  path: '/explore/legos',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/games': typeof SiteGamesRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/visit': typeof SiteVisitRoute
  '/explore/comics': typeof SiteExploreComicsRoute
  '/explore/events': typeof SiteExploreEventsRoute
  '/explore/food': typeof SiteExploreFoodRoute
  '/explore/legos': typeof SiteExploreLegosRoute
  '/explore/': typeof SiteExploreIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/games': typeof SiteGamesRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/visit': typeof SiteVisitRoute
  '/': typeof SiteIndexRoute
  '/explore/comics': typeof SiteExploreComicsRoute
  '/explore/events': typeof SiteExploreEventsRoute
  '/explore/food': typeof SiteExploreFoodRoute
  '/explore/legos': typeof SiteExploreLegosRoute
  '/explore': typeof SiteExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/cookies': typeof SiteCookiesRoute
  '/_site/games': typeof SiteGamesRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/visit': typeof SiteVisitRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/explore/comics': typeof SiteExploreComicsRoute
  '/_site/explore/events': typeof SiteExploreEventsRoute
  '/_site/explore/food': typeof SiteExploreFoodRoute
  '/_site/explore/legos': typeof SiteExploreLegosRoute
  '/_site/explore/': typeof SiteExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/cookies'
    | '/games'
    | '/privacy'
    | '/terms'
    | '/visit'
    | '/explore/comics'
    | '/explore/events'
    | '/explore/food'
    | '/explore/legos'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/contact'
    | '/cookies'
    | '/games'
    | '/privacy'
    | '/terms'
    | '/visit'
    | '/'
    | '/explore/comics'
    | '/explore/events'
    | '/explore/food'
    | '/explore/legos'
    | '/explore'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/contact'
    | '/_site/cookies'
    | '/_site/games'
    | '/_site/privacy'
    | '/_site/terms'
    | '/_site/visit'
    | '/_site/'
    | '/_site/explore/comics'
    | '/_site/explore/events'
    | '/_site/explore/food'
    | '/_site/explore/legos'
    | '/_site/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cookies': {
      id: '/_site/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof SiteCookiesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/games': {
      id: '/_site/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof SiteGamesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/visit': {
      id: '/_site/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof SiteVisitRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/explore/': {
      id: '/_site/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof SiteExploreIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/explore/comics': {
      id: '/_site/explore/comics'
      path: '/explore/comics'
      fullPath: '/explore/comics'
      preLoaderRoute: typeof SiteExploreComicsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/explore/events': {
      id: '/_site/explore/events'
      path: '/explore/events'
      fullPath: '/explore/events'
      preLoaderRoute: typeof SiteExploreEventsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/explore/food': {
      id: '/_site/explore/food'
      path: '/explore/food'
      fullPath: '/explore/food'
      preLoaderRoute: typeof SiteExploreFoodRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/explore/legos': {
      id: '/_site/explore/legos'
      path: '/explore/legos'
      fullPath: '/explore/legos'
      preLoaderRoute: typeof SiteExploreLegosRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContactRoute: typeof SiteContactRoute
  SiteCookiesRoute: typeof SiteCookiesRoute
  SiteGamesRoute: typeof SiteGamesRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteVisitRoute: typeof SiteVisitRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteExploreComicsRoute: typeof SiteExploreComicsRoute
  SiteExploreEventsRoute: typeof SiteExploreEventsRoute
  SiteExploreFoodRoute: typeof SiteExploreFoodRoute
  SiteExploreLegosRoute: typeof SiteExploreLegosRoute
  SiteExploreIndexRoute: typeof SiteExploreIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContactRoute: SiteContactRoute,
  SiteCookiesRoute: SiteCookiesRoute,
  SiteGamesRoute: SiteGamesRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteVisitRoute: SiteVisitRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteExploreComicsRoute: SiteExploreComicsRoute,
  SiteExploreEventsRoute: SiteExploreEventsRoute,
  SiteExploreFoodRoute: SiteExploreFoodRoute,
  SiteExploreLegosRoute: SiteExploreLegosRoute,
  SiteExploreIndexRoute: SiteExploreIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
